---

- name: install scope
  command: curl -L git.io/scope -o /usr/local/bin/scope
  become: true

- name: make scope executable
  command: chmod a+x /usr/local/bin/scope
  become: true

#- debug: var=hostvars['internal-swarm-01.ip']

- name: get IPs of all nodes
  set_fact:
    allips: |
      {% set comma = joiner(" ") %}
      {% for host in groups['docker_engine'] -%}
        {{ comma() }}{{ hostvars[host]['ansible_default_ipv4']['address']}}
      {%- endfor -%}

- name: launch scope
  command: "scope launch {{ allips }}"
  ignore_errors: yes
