- hosts: "ds-elastic.ys.com"
  become: true
  roles:
    - { role: setup_elasticsearch, es_instance_name: "es-1", es_config: { discovery.zen.ping.unicast.hosts: "ds-elastic.ys.com", network.host: "0.0.0.0", cluster.name: "elastic", http.port: 9200, transport.tcp.port: 9300, node.data: true, node.master: true } }
  vars:
    es_heap_size: "1g"
    es_cluster_name: "elastic"
